//
// Created by smary on 26.03.2023.
//

#ifndef DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_2_HPP
#define DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_2_HPP
#include "dop2.2.hpp"
void modelprog2(FILE* file1, FILE* file2);
#endif //DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_2_HPP
