//
// Created by smary on 27.03.2023.
//

#ifndef DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_4_HPP
#define DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_4_HPP

#include <cstdio>
#include "dop2.4.hpp"
void modelprog5(FILE* file1,FILE* file2);
#endif //DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_4_HPP
