//
// Created by smary on 26.03.2023.
//

#ifndef DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_1_HPP
#define DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_1_HPP
#include "dop2.1.hpp"
void modelprog1(FILE* file1, FILE* file2);
#endif //DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_1_HPP
