//
// Created by smary on 26.03.2023.
//

#ifndef DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_3_HPP
#define DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_3_HPP
#include "dop2.3.hpp"
void modelprog3(FILE* file1, FILE* file2);
void modelprog4(FILE* file1, FILE* file2);
#endif //DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_3_HPP
