//
// Created by smary on 27.03.2023.
//

#ifndef DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_5_HPP
#define DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_5_HPP
#include "dop2.5.hpp"
void modelprog6(FILE* file1,FILE* file2);
#endif //DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_DOP2_5_HPP
