//
// Created by smary on 04.04.2023.
//

#ifndef DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_OSNOVA4_HPP
#define DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_OSNOVA4_HPP
#include "osnova4.hpp"
void osnova4(FILE* file);
#endif //DATATRANSMISSIONINSYSTEMSWITHFEEDBACK_OSNOVA4_HPP
